// +build !ignore_autogenerated

// Code generated by collections-gen. DO NOT EDIT.

package immutable

import (
	"sort"
)

// ImmutableFooCollection is an immutable collection of Foo values.
type ImmutableFooCollection struct {
	items []Foo
}

// NewImmutableFooCollection creates a new immutable collection from a slice of Foo.
func NewImmutableFooCollection(items []Foo) *ImmutableFooCollection {
	return &ImmutableFooCollection{items}
}

// Interface returns the underlying slice used by the collection as interface{}
// value.
func (c *ImmutableFooCollection) Interface() interface{} {
	return c.items
}

// Items returns the underlying slice of Foo values used by the
// collection.
func (c *ImmutableFooCollection) Items() []Foo {
	return c.items
}

// EachIndex calls fn for every item in the collection. The slice index of the
// item is passed to fn as the second argument.
func (c *ImmutableFooCollection) EachIndex(fn func(Foo, int)) {
	for i, item := range c.items {
		fn(item, i)
	}
}

// Each calls fn for every item in the collection.
func (c *ImmutableFooCollection) Each(fn func(Foo)) {
	c.EachIndex(func(item Foo, _ int) {
		fn(item)
	})
}

// IndexOf searches for el in the collection and returns the first index where
// el is found. If el is not present in the collection IndexOf will return -1.
func (c *ImmutableFooCollection) IndexOf(el Foo) int {
	for i, item := range c.items {
		if item == el {
			return i
		}
	}

	return -1
}

// First returns the first item from the collection. Will panic if the
// underlying slice is empty.
func (c *ImmutableFooCollection) First() Foo {
	return c.Nth(0)
}

// FirstN returns the first n Foo items of the collection. Will
// return less than n items if the underlying slice's length is < n.
func (c *ImmutableFooCollection) FirstN(n int) []Foo {
	if n > c.Len() {
		return c.Copy().Items()
	}

	return c.Slice(0, n)
}

// Last returns the last item from the collection. Will panic if the underlying
// slice is empty.
func (c *ImmutableFooCollection) Last() Foo {
	return c.Nth(c.Len() - 1)
}

// LastN returns the last n Foo items of the collection. Will return
// less than n items if the underlying slice's length is < n.
func (c *ImmutableFooCollection) LastN(n int) []Foo {
	if c.Len()-n < 0 {
		return c.Copy().Items()
	}

	return c.Slice(c.Len()-n, c.Len())
}

// Get returns the item at pos from the collection. Will panic if the
// underlying slice is shorter than pos+1.
func (c *ImmutableFooCollection) Get(pos int) Foo {
	return c.Nth(pos)
}

// Nth returns the nth item from the collection. Will panic if the underlying
// slice is shorter than pos+1.
func (c *ImmutableFooCollection) Nth(pos int) Foo {
	return c.items[pos]
}

// Len returns the length of the underlying Foo slice.
func (c *ImmutableFooCollection) Len() int {
	return len(c.items)
}

// Cap returns the capacity of the underlying Foo slice.
func (c *ImmutableFooCollection) Cap() int {
	return cap(c.items)
}

// Append appends items and returns the collection. The
// original collection will not be modified.
func (c *ImmutableFooCollection) Append(items ...Foo) *ImmutableFooCollection {
	d := c.Copy()
	d.items = append(d.items, items...)
	return d
}

// Prepend prepends items and returns the collection. The
// original collection will not be modified.
func (c *ImmutableFooCollection) Prepend(items ...Foo) *ImmutableFooCollection {
	d := c.Copy()
	d.items = append(items, d.items...)
	return d
}

// Copy creates a copy of the collection and the underlying Foo slice.
func (c *ImmutableFooCollection) Copy() *ImmutableFooCollection {
	s := make([]Foo, c.Len(), c.Len())
	copy(s, c.items)

	return NewImmutableFooCollection(s)
}

// Filter collects all items for which fn evaluates to true into a new
// collection. The original collection is not altered.
func (c *ImmutableFooCollection) Filter(fn func(Foo) bool) *ImmutableFooCollection {
	d := c.Copy()
	s := d.items[:0]

	for _, item := range d.items {
		if fn(item) {
			s = append(s, item)
		}
	}

	var zeroValue Foo

	for i := len(s); i < len(d.items); i++ {
		d.items[i] = zeroValue
	}

	d.items = s

	return d
}

// Collect collects all items for which fn evaluates to true into a new
// collection. The original collection is not altered.
func (c *ImmutableFooCollection) Collect(fn func(Foo) bool) *ImmutableFooCollection {
	return c.Filter(fn)
}

// Reject collects all items for which fn evaluates to false into a new
// collection. The original collection is not altered.
func (c *ImmutableFooCollection) Reject(fn func(Foo) bool) *ImmutableFooCollection {
	return c.Filter(func(v Foo) bool {
		return !fn(v)
	})
}

// Partition partitions the collection into two new collections. The first
// collection contains all items where fn evaluates to true, the second one all
// items where fn evaluates to false.
func (c *ImmutableFooCollection) Partition(fn func(Foo) bool) (*ImmutableFooCollection, *ImmutableFooCollection) {
	lhs := make([]Foo, 0, c.Len())
	rhs := make([]Foo, 0, c.Len())

	for _, item := range c.items {
		if fn(item) {
			lhs = append(lhs, item)
		} else {
			rhs = append(rhs, item)
		}
	}

	return NewImmutableFooCollection(lhs), NewImmutableFooCollection(rhs)
}

// Map calls fn for each item in the collection an replaces its value with the
// result of fn. The result is a new collection. The original
// collection is not modified.
func (c *ImmutableFooCollection) Map(fn func(Foo) Foo) *ImmutableFooCollection {
	return c.MapIndex(func(item Foo, _ int) Foo {
		return fn(item)
	})
}

// MapIndex calls fn for each item in the collection an replaces its value with the
// result of fn. The result is a new collection. The original
// collection is not modified.
func (c *ImmutableFooCollection) MapIndex(fn func(Foo, int) Foo) *ImmutableFooCollection {
	d := c.Copy()

	for i, item := range d.items {
		d.items[i] = fn(item, i)

	}

	return d
}

// Reduce calls fn for each item in c and reduces the result into reducer. The
// reducer contains the value returned by the call to fn for the previous item.
// Reducer will be the zero Foo value on the first invocation.
func (c *ImmutableFooCollection) Reduce(fn func(reducer Foo, item Foo) Foo) Foo {
	var reducer Foo

	for _, item := range c.items {
		reducer = fn(reducer, item)
	}

	return reducer
}

// Find returns the first item for which fn evaluates to true. If the
// collection does not contain a matching item, Find will return the zero
// Foo value. If you need to distinguish zero values from a condition
// that did not match any item consider using FindOk instead.
func (c *ImmutableFooCollection) Find(fn func(Foo) bool) Foo {
	item, _ := c.FindOk(fn)

	return item
}

// FindOk returns the first item for which fn evaluates to true. If the
// collection does not contain a matching item, FindOk will return the zero
// Foo value. The second return value denotes whether the condition
// matched any item or not.
func (c *ImmutableFooCollection) FindOk(fn func(Foo) bool) (Foo, bool) {
	for _, item := range c.items {
		if fn(item) {
			return item, true
		}
	}

	var zeroValue Foo
	return zeroValue, false
}

// Any returns true as soon as fn evaluates to true for one item in c.
func (c *ImmutableFooCollection) Any(fn func(Foo) bool) bool {
	for _, item := range c.items {
		if fn(item) {
			return true
		}
	}

	return false
}

// All returns true if fn evaluates to true for all items in c.
func (c *ImmutableFooCollection) All(fn func(Foo) bool) bool {
	for _, item := range c.items {
		if !fn(item) {
			return false
		}
	}

	return true
}

// Contains returns true if the collection contains el.
func (c *ImmutableFooCollection) Contains(el Foo) bool {
	for _, item := range c.items {
		if item == el {
			return true
		}
	}

	return false
}

// Sort sorts the collection using the passed in comparator func.
// The result will be a copy of c which is sorted, the original collection is
// not altered.
func (c *ImmutableFooCollection) Sort(fn func(Foo, Foo) bool) *ImmutableFooCollection {
	d := c.Copy()
	sort.Slice(d.items, d.lessFunc(fn))
	return d
}

// IsSorted returns true if the collection is sorted in the order defined by
// the passed in comparator func.
func (c *ImmutableFooCollection) IsSorted(fn func(Foo, Foo) bool) bool {
	return sort.SliceIsSorted(c.items, c.lessFunc(fn))
}

func (c *ImmutableFooCollection) lessFunc(fn func(Foo, Foo) bool) func(int, int) bool {
	return func(i, j int) bool {
		return fn(c.items[i], c.items[j])
	}
}

// Reverse copies the collection and returns it with the order of all items
// reversed.
func (c *ImmutableFooCollection) Reverse() *ImmutableFooCollection {
	d := c.Copy()
	for l, r := 0, len(d.items)-1; l < r; l, r = l+1, r-1 {
		d.items[l], d.items[r] = d.items[r], d.items[l]
	}

	return d
}

// Remove removes the collection item at position pos. Will panic if pos is out
// of bounds.
// The result is a new collection, the original is not modified.
func (c *ImmutableFooCollection) Remove(pos int) *ImmutableFooCollection {
	d := c.Copy()
	d.items = append(d.items[:pos], d.items[pos+1:]...)
	return d
}

// RemoveItem removes all instances of item from the collection and returns it.
// The result is a new collection, the original is not modified.
func (c *ImmutableFooCollection) RemoveItem(item Foo) *ImmutableFooCollection {
	d := c.Copy()

	for i, el := range d.items {
		if el == item {
			d.items = append(d.items[:i], d.items[i+1:]...)
		}
	}

	return d
}

// InsertItem inserts item into the collection at position pos. Will panic if
// pos is out of bounds.
// The result is a new collection, the original is not modified.
func (c *ImmutableFooCollection) InsertItem(item Foo, pos int) *ImmutableFooCollection {
	var zeroValue Foo
	d := c.Copy()
	d.items = append(d.items, zeroValue)
	copy(d.items[pos+1:], d.items[pos:])
	d.items[pos] = item
	return d
}

// Cut returns a copy of the underlying Foo slice with the items
// between index i and j removed. Will panic if i or j is out of bounds of the
// underlying slice.
func (c *ImmutableFooCollection) Cut(i, j int) []Foo {
	d := c.Copy()
	return append(d.items[:i], d.items[j:]...)
}

// Slice returns the Foo items between slice index i and j. Will
// panic if i or j is out of bounds.
func (c *ImmutableFooCollection) Slice(i, j int) []Foo {
	return c.Copy().items[i:j]
}
