// +build !ignore_autogenerated

// Code generated by collections-gen. DO NOT EDIT.

package underlying

import (
	"io"
	"reflect"
	"sort"
)

// WriterMapCollection is a collection of map[string]io.Writer values.
type WriterMapCollection struct {
	items []map[string]io.Writer
}

// NewWriterMapCollection creates a new collection from a slice of map[string]io.Writer.
func NewWriterMapCollection(items []map[string]io.Writer) *WriterMapCollection {
	return &WriterMapCollection{items}
}

// Interface returns the underlying slice used by the collection as interface{}
// value.
func (c *WriterMapCollection) Interface() interface{} {
	return c.items
}

// Items returns the underlying slice of map[string]io.Writer values used by the
// collection.
func (c *WriterMapCollection) Items() []map[string]io.Writer {
	return c.items
}

// EachIndex calls fn for every item in the collection. The slice index of the
// item is passed to fn as the second argument.
func (c *WriterMapCollection) EachIndex(fn func(map[string]io.Writer, int)) {
	for i, item := range c.items {
		fn(item, i)
	}
}

// Each calls fn for every item in the collection.
func (c *WriterMapCollection) Each(fn func(map[string]io.Writer)) {
	c.EachIndex(func(item map[string]io.Writer, _ int) {
		fn(item)
	})
}

// IndexOf searches for el in the collection and returns the first index where
// el is found. If el is not present in the collection IndexOf will return -1.
func (c *WriterMapCollection) IndexOf(el map[string]io.Writer) int {
	for i, item := range c.items {
		if reflect.DeepEqual(item, el) {
			return i
		}
	}

	return -1
}

// First returns the first item from the collection. Will panic if the
// underlying slice is empty.
func (c *WriterMapCollection) First() map[string]io.Writer {
	return c.Nth(0)
}

// FirstN returns the first n map[string]io.Writer items of the collection. Will
// return less than n items if the underlying slice's length is < n.
func (c *WriterMapCollection) FirstN(n int) []map[string]io.Writer {
	if n > c.Len() {
		return c.Items()
	}

	return c.Slice(0, n)
}

// Last returns the last item from the collection. Will panic if the underlying
// slice is empty.
func (c *WriterMapCollection) Last() map[string]io.Writer {
	return c.Nth(c.Len() - 1)
}

// LastN returns the last n map[string]io.Writer items of the collection. Will return
// less than n items if the underlying slice's length is < n.
func (c *WriterMapCollection) LastN(n int) []map[string]io.Writer {
	if c.Len()-n < 0 {
		return c.Items()
	}

	return c.Slice(c.Len()-n, c.Len())
}

// Get returns the item at pos from the collection. Will panic if the
// underlying slice is shorter than pos+1.
func (c *WriterMapCollection) Get(pos int) map[string]io.Writer {
	return c.Nth(pos)
}

// Nth returns the nth item from the collection. Will panic if the underlying
// slice is shorter than pos+1.
func (c *WriterMapCollection) Nth(pos int) map[string]io.Writer {
	return c.items[pos]
}

// Len returns the length of the underlying map[string]io.Writer slice.
func (c *WriterMapCollection) Len() int {
	return len(c.items)
}

// Cap returns the capacity of the underlying map[string]io.Writer slice.
func (c *WriterMapCollection) Cap() int {
	return cap(c.items)
}

// Append appends items and returns the collection.
func (c *WriterMapCollection) Append(items ...map[string]io.Writer) *WriterMapCollection {
	c.items = append(c.items, items...)
	return c
}

// Prepend prepends items and returns the collection.
func (c *WriterMapCollection) Prepend(items ...map[string]io.Writer) *WriterMapCollection {
	c.items = append(items, c.items...)
	return c
}

// Copy creates a copy of the collection and the underlying map[string]io.Writer slice.
func (c *WriterMapCollection) Copy() *WriterMapCollection {
	s := make([]map[string]io.Writer, c.Len(), c.Len())
	copy(s, c.items)

	return NewWriterMapCollection(s)
}

// Filter removes all items from the collection for which fn evaluates to
// false and returns c.
func (c *WriterMapCollection) Filter(fn func(map[string]io.Writer) bool) *WriterMapCollection {
	s := c.items[:0]

	for _, item := range c.items {
		if fn(item) {
			s = append(s, item)
		}
	}

	var zeroValue map[string]io.Writer

	for i := len(s); i < len(c.items); i++ {
		c.items[i] = zeroValue
	}

	c.items = s

	return c
}

// Collect removes all items from the collection for which fn evaluates to
// false and returns c.
func (c *WriterMapCollection) Collect(fn func(map[string]io.Writer) bool) *WriterMapCollection {
	return c.Filter(fn)
}

// Reject removes all items from the collection for which fn evaluates to
// true and returns c.
func (c *WriterMapCollection) Reject(fn func(map[string]io.Writer) bool) *WriterMapCollection {
	return c.Filter(func(v map[string]io.Writer) bool {
		return !fn(v)
	})
}

// Partition partitions the collection into two new collections. The first
// collection contains all items where fn evaluates to true, the second one all
// items where fn evaluates to false.
func (c *WriterMapCollection) Partition(fn func(map[string]io.Writer) bool) (*WriterMapCollection, *WriterMapCollection) {
	lhs := make([]map[string]io.Writer, 0, c.Len())
	rhs := make([]map[string]io.Writer, 0, c.Len())

	for _, item := range c.items {
		if fn(item) {
			lhs = append(lhs, item)
		} else {
			rhs = append(rhs, item)
		}
	}

	return NewWriterMapCollection(lhs), NewWriterMapCollection(rhs)
}

// Map calls fn for each item in the collection an replaces its value with the
// result of fn.
func (c *WriterMapCollection) Map(fn func(map[string]io.Writer) map[string]io.Writer) *WriterMapCollection {
	return c.MapIndex(func(item map[string]io.Writer, _ int) map[string]io.Writer {
		return fn(item)
	})
}

// MapIndex calls fn for each item in the collection an replaces its value with the
// result of fn.
func (c *WriterMapCollection) MapIndex(fn func(map[string]io.Writer, int) map[string]io.Writer) *WriterMapCollection {
	for i, item := range c.items {
		c.items[i] = fn(item, i)

	}

	return c
}

// Reduce calls fn for each item in c and reduces the result into reducer. The
// reducer contains the value returned by the call to fn for the previous item.
// Reducer will be the zero map[string]io.Writer value on the first invocation.
func (c *WriterMapCollection) Reduce(fn func(reducer map[string]io.Writer, item map[string]io.Writer) map[string]io.Writer) map[string]io.Writer {
	var reducer map[string]io.Writer

	for _, item := range c.items {
		reducer = fn(reducer, item)
	}

	return reducer
}

// Find returns the first item for which fn evaluates to true. If the
// collection does not contain a matching item, Find will return the zero
// map[string]io.Writer value. If you need to distinguish zero values from a condition
// that did not match any item consider using FindOk instead.
func (c *WriterMapCollection) Find(fn func(map[string]io.Writer) bool) map[string]io.Writer {
	item, _ := c.FindOk(fn)

	return item
}

// FindOk returns the first item for which fn evaluates to true. If the
// collection does not contain a matching item, FindOk will return the zero
// map[string]io.Writer value. The second return value denotes whether the condition
// matched any item or not.
func (c *WriterMapCollection) FindOk(fn func(map[string]io.Writer) bool) (map[string]io.Writer, bool) {
	for _, item := range c.items {
		if fn(item) {
			return item, true
		}
	}

	var zeroValue map[string]io.Writer
	return zeroValue, false
}

// Any returns true as soon as fn evaluates to true for one item in c.
func (c *WriterMapCollection) Any(fn func(map[string]io.Writer) bool) bool {
	for _, item := range c.items {
		if fn(item) {
			return true
		}
	}

	return false
}

// All returns true if fn evaluates to true for all items in c.
func (c *WriterMapCollection) All(fn func(map[string]io.Writer) bool) bool {
	for _, item := range c.items {
		if !fn(item) {
			return false
		}
	}

	return true
}

// Contains returns true if the collection contains el.
func (c *WriterMapCollection) Contains(el map[string]io.Writer) bool {
	for _, item := range c.items {
		if reflect.DeepEqual(item, el) {
			return true
		}
	}

	return false
}

// Sort sorts the collection using the passed in comparator func.
func (c *WriterMapCollection) Sort(fn func(map[string]io.Writer, map[string]io.Writer) bool) *WriterMapCollection {
	sort.Slice(c.items, c.lessFunc(fn))
	return c
}

// IsSorted returns true if the collection is sorted in the order defined by
// the passed in comparator func.
func (c *WriterMapCollection) IsSorted(fn func(map[string]io.Writer, map[string]io.Writer) bool) bool {
	return sort.SliceIsSorted(c.items, c.lessFunc(fn))
}

func (c *WriterMapCollection) lessFunc(fn func(map[string]io.Writer, map[string]io.Writer) bool) func(int, int) bool {
	return func(i, j int) bool {
		return fn(c.items[i], c.items[j])
	}
}

// Reverse reverses the order of the collection items in place and returns c.
func (c *WriterMapCollection) Reverse() *WriterMapCollection {
	for l, r := 0, len(c.items)-1; l < r; l, r = l+1, r-1 {
		c.items[l], c.items[r] = c.items[r], c.items[l]
	}

	return c
}

// Remove removes the collection item at position pos. Will panic if pos is out
// of bounds.
func (c *WriterMapCollection) Remove(pos int) *WriterMapCollection {
	c.items = append(c.items[:pos], c.items[pos+1:]...)
	return c
}

// RemoveItem removes all instances of item from the collection and returns it.
func (c *WriterMapCollection) RemoveItem(item map[string]io.Writer) *WriterMapCollection {
	for i, el := range c.items {
		if reflect.DeepEqual(el, item) {
			c.items = append(c.items[:i], c.items[i+1:]...)
		}
	}

	return c
}

// InsertItem inserts item into the collection at position pos. Will panic if
// pos is out of bounds.
func (c *WriterMapCollection) InsertItem(item map[string]io.Writer, pos int) *WriterMapCollection {
	var zeroValue map[string]io.Writer
	c.items = append(c.items, zeroValue)
	copy(c.items[pos+1:], c.items[pos:])
	c.items[pos] = item
	return c
}

// Cut returns a copy of the underlying map[string]io.Writer slice with the items
// between index i and j removed. Will panic if i or j is out of bounds of the
// underlying slice.
func (c *WriterMapCollection) Cut(i, j int) []map[string]io.Writer {
	s := make([]map[string]io.Writer, 0, c.Len())
	s = append(s, c.items[:i]...)
	return append(s, c.items[j:]...)
}

// Slice returns the map[string]io.Writer items between slice index i and j. Will
// panic if i or j is out of bounds.
func (c *WriterMapCollection) Slice(i, j int) []map[string]io.Writer {
	return c.items[i:j]
}
